### ISSUE TITLE
complete example

### ISSUE THREAD

**Issue by cforce** [jmnarloch/feign-vnderror-spring-cloud-starter#2]
Would you add an real world example how this be used on the server side and client side if having content type application/json for the 200 ok case?
Is there a way where i could use Feign Error Decoder so wrap the VND expcetion propagation inside Feign, so it would throw the original exception (beeing wrapped on server side) on client side again?
The Feign Error  Decoder shall make use of the same mapping and Codes as the server uses them.
Please show an example How can i make use of the error/exception propagation in a case where using Feign microservice 1 is calling microservice 2 is calling microservice 3  throwing the excepion MyException back to microservice 2 back microservice 1 where MyException raises in Java Code.
The idea is great but i have to really understood ist right from existing test code.

**Comment by jmnarloch** [comment]
Closing this is the duplication of the first issue
